var currenciesJSON = 
{
	BTC: { name: 'Bitcoin' },
	WBTC: { name: 'Wrapped Bitcoin' },
	BCH: { name: 'Bitcoin Cash' },
	BSV: { name: 'Bitcoin SV' },
	BTG: { name: 'Bitcoin Gold' },
	'BTC.B': { name: 'Bitcoin Avalanche Bridged (BTC.b)' },
	ETH: { name: 'Ethereum' },
	ETC: { name: 'Ethereum Classic' },
	ETHW: { name: 'EthereumPoW' },
	ENS: { name: 'Ethereum Name Service' },
	USDT: { name: 'Tether' },
	BNB: { name: 'BNB' },
	USDC: { name: 'USD Coin' },
	XRP: { name: 'XRP' },
	ADA: { name: 'Cardano' },
	DOGE: { name: 'Dogecoin' },
	STETH: { name: 'Lido Staked Ether' },
	MATIC: { name: 'Polygon' },
	BUSD: { name: 'Binance USD' },
	SOL: { name: 'Solana' },
	DOT: { name: 'Polkadot' },
	LTC: { name: 'Litecoin' },
	SHIB: { name: 'Shiba Inu' },
	TRX: { name: 'TRON' },
	AVAX: { name: 'Avalanche' },
	DAI: { name: 'Dai' },
	UNI: { name: 'Uniswap' },
	LINK: { name: 'Chainlink' },
	ATOM: { name: 'Cosmos Hub' },
	LEO: { name: 'LEO Token' },
	TON: { name: 'Toncoin' },
	XMR: { name: 'Monero' },
	OKB: { name: 'OKB' },
	XLM: { name: 'Stellar' },
	FIL: { name: 'Filecoin' },
	APT: { name: 'Aptos' },
	TUSD: { name: 'TrueUSD' },
	HBAR: { name: 'Hedera' },
	LDO: { name: 'Lido DAO' },
	QNT: { name: 'Quant' },
	CRO: { name: 'Cronos' },
	NEAR: { name: 'NEAR Protocol' },
	VET: { name: 'VeChain' },
	ARB: { name: 'Arbitrum' },
	APE: { name: 'ApeCoin' },
	ALGO: { name: 'Algorand' },
	ICP: { name: 'Internet Computer' },
	STX: { name: 'Stacks' },
	EOS: { name: 'EOS' },
	GRT: { name: 'The Graph' },
	FTM: { name: 'Fantom' },
	SAND: { name: 'The Sandbox' },
	MANA: { name: 'Decentraland' },
	EGLD: { name: 'MultiversX' },
	FRAX: { name: 'Frax' },
	XTZ: { name: 'Tezos' },
	AAVE: { name: 'Aave' },
	FLOW: { name: 'Flow' },
	THETA: { name: 'Theta Network' },
	IMX: { name: 'ImmutableX' },
	AXS: { name: 'Axie Infinity' },
	NEO: { name: 'NEO' },
	KCS: { name: 'KuCoin' },
	USDP: { name: 'Pax Dollar' },
	SNX: { name: 'Synthetix Network' },
	BIT: { name: 'BitDAO' },
	WBT: { name: 'WhiteBIT Token' },
	RPL: { name: 'Rocket Pool' },
	GT: { name: 'Gate' },
	LUNC: { name: 'Terra Luna Classic' },
	USDD: { name: 'USDD' },
	MINA: { name: 'Mina Protocol' },
	OP: { name: 'Optimism' },
	CRV: { name: 'Curve DAO' },
	KLAY: { name: 'Klaytn' },
	CAKE: { name: 'PancakeSwap' },
	CFX: { name: 'Conflux' },
	DASH: { name: 'Dash' },
	CHZ: { name: 'Chiliz' },
	GMX: { name: 'GMX' },
	MKR: { name: 'Maker' },
	XEC: { name: 'eCash' },
	HT: { name: 'Huobi' },
	BTT: { name: 'BitTorrent' },
	MIOTA: { name: 'IOTA' },
	AGIX: { name: 'SingularityNET' },
	FXS: { name: 'Frax Share' },
	BGB: { name: 'Bitget Token' },
	XDC: { name: 'XDC Network' },
	CETH: { name: 'cETH' },
	EDGT: { name: 'Edgecoin' },
	PAXG: { name: 'PAX Gold' },
	TWT: { name: 'Trust Wallet' },
	TKX: { name: 'Tokenize Xchange' },
	XAUT: { name: 'Tether Gold' },
	ZIL: { name: 'Zilliqa' },
	CUSDC: { name: 'cUSDC' },
	MASK: { name: 'Mask Network' },
	OSMO: { name: 'Osmosis' },
	FLR: { name: 'Flare' },
	XRD: { name: 'Radix' },
	RNDR: { name: 'Render' },
	LRC: { name: 'Loopring' },
	'1INCH': { name: '1inch' },
	RUNE: { name: 'THORChain' },
	NEXO: { name: 'NEXO' },
	RETH: { name: 'Rocket Pool ETH' },
	KAVA: { name: 'Kava' },
	AR: { name: 'Arweave' },
	GUSD: { name: 'Gemini Dollar' },
	OKT: { name: 'OKC Token' },
	CDAI: { name: 'cDAI' },
	ENJ: { name: 'Enjin Coin' },
	CSPR: { name: 'Casper Network' },
	CVX: { name: 'Convex Finance' },
	BTSE: { name: 'BTSE Token' },
	FET: { name: 'Fetch.ai' },
	ZEC: { name: 'Zcash' },
	DFI: { name: 'DeFiChain' },
	DYDX: { name: 'dYdX' },
	BAT: { name: 'Basic Attention' },
	XEM: { name: 'NEM' },
	FLOKI: { name: 'FLOKI' },
	WEMIX: { name: 'WEMIX' },
	NXM: { name: 'Nexus Mutual' },
	WOO: { name: 'WOO Network' },
	BABYDOGE: { name: 'Baby Doge Coin' },
	QTUM: { name: 'Qtum' },
	INJ: { name: 'Injective' },
	AZERO: { name: 'Aleph Zero' },
	TFUEL: { name: 'Theta Fuel' },
	DCR: { name: 'Decred' },
	HOT: { name: 'Holo' },
	LUNA: { name: 'Terra' },
	BDX: { name: 'Beldex' },
	MAGIC: { name: 'Magic' },
	RVN: { name: 'Ravencoin' },
	KSM: { name: 'Kusama' },
	CELO: { name: 'Celo' },
	GALA: { name: 'GALA' },
	KAS: { name: 'Kaspa' },
	COMP: { name: 'Compound' },
	GFARM2: { name: 'Gains Farm' },
	ROSE: { name: 'Oasis Network' },
	OHM: { name: 'Olympus' },
	GNO: { name: 'Gnosis' },
	SAFEMOON: { name: 'SafeMoon [OLD]' },
	LN: { name: 'LINK' },
	YFI: { name: 'yearn.finance' },
	ASTR: { name: 'Astar' },
	ACS: { name: 'Access Protocol' },
	ANKR: { name: 'Ankr Network' },
	BAL: { name: 'Balancer' },
	LUSD: { name: 'Liquity USD' },
	OMG: { name: 'OMG Network' },
	AUDIO: { name: 'Audius' },
	XCH: { name: 'Chia' },
	BONE: { name: 'Bone ShibaSwap' },
	NU: { name: 'NuCypher' },
	ONE: { name: 'Harmony' },
	HBTC: { name: 'Huobi BTC' },
	SSV: { name: 'SSV Network' },
	GMT: { name: 'STEPN' },
	IOTX: { name: 'IoTeX' },
	ASTRAFER: { name: 'Astrafer' },
	GLM: { name: 'Golem' },
	CVXCRV: { name: 'Convex CRV' },
	JST: { name: 'JUST' },
	ELG: { name: 'Escoin' },
	DAO: { name: 'DAO Maker' },
	BAND: { name: 'Band Protocol' },
	GLMR: { name: 'Moonbeam' },
	BLUR: { name: 'Blur' },
	EURT: { name: 'Euro Tether' },
	JASMY: { name: 'JasmyCoin' },
	GNS: { name: 'Gains Network' },
	CDT: { name: 'Blox' },
	FRXETH: { name: 'Frax Ether' },
	OMI: { name: 'ECOMI' },
	KDA: { name: 'Kadena' },
	AMP: { name: 'Amp' },
	WAVES: { name: 'Waves' },
	ICX: { name: 'ICON' },
	SC: { name: 'Siacoin' },
	USTC: { name: 'TerraClassicUSD' },
	HNT: { name: 'Helium' },
	BRISE: { name: 'Bitgert' },
	SUSHI: { name: 'Sushi' },
	ONT: { name: 'Ontology' },
	LQTY: { name: 'Liquity' },
	MX: { name: 'MX' },
	IOST: { name: 'IOST' },
	ELON: { name: 'Dogelon Mars' },
	ZRX: { name: '0x' },
	FLEX: { name: 'FLEX Coin' },
	CKB: { name: 'Nervos Network' },
	ECOIN: { name: 'Ecoin' },
	LPT: { name: 'Livepeer' },
	BICO: { name: 'Biconomy' },
	MULTI: { name: 'Multichain' },
	RSR: { name: 'Reserve Rights' },
	FLUX: { name: 'Flux' },
	SKL: { name: 'SKALE' },
	ALUSD: { name: 'Alchemix USD' },
	BORA: { name: 'BORA' },
	WAXP: { name: 'WAX' },
	CHSB: { name: 'SwissBorg' },
	TOMI: { name: 'tomiNet' },
	SFP: { name: 'SafePal' },
	POLY: { name: 'Polymath' },
	EWT: { name: 'Energy Web' },
	ACH: { name: 'Alchemy Pay' },
	SYN: { name: 'Synapse' },
	SURE: { name: 'inSure DeFi' },
	EVMOS: { name: 'Evmos' },
	LSK: { name: 'Lisk' },
	TEL: { name: 'Telcoin' },
	KUB: { name: 'Bitkub Coin' },
	CELR: { name: 'Celer Network' },
	OCEAN: { name: 'Ocean Protocol' },
	DGB: { name: 'DigiByte' },
	BLID: { name: 'Bolide' },
	EVER: { name: 'Everscale' },
	SXP: { name: 'SXP' },
	HIVE: { name: 'Hive' },
	CORE: { name: 'Core' },
	ILV: { name: 'Illuvium' },
	CEL: { name: 'Celsius Network' },
	ELF: { name: 'aelf' },
	UMA: { name: 'UMA' },
	TRAC: { name: 'OriginTrail' },
	ALI: { name: 'Artificial Liquid Intelligence' },
	SFM: { name: 'SafeMoon' },
	RBN: { name: 'Ribbon Finance' },
	ZEN: { name: 'Horizen' },
	SFRXETH: { name: 'Staked Frax Ether' },
	RLC: { name: 'iExec RLC' },
	EURS: { name: 'STASIS EURO' },
	ID: { name: 'SPACE ID' },
	GTC: { name: 'Gitcoin' },
	FUC: { name: 'FUBT Token' },
	LYXE: { name: 'LUKSO' },
	SETH2: { name: 'sETH2' },
	DAG: { name: 'Constellation' },
	SCRT: { name: 'Secret' },
	JOE: { name: 'JOE' },
	AXL: { name: 'Axelar' },
	TRIBE: { name: 'Tribe' },
	POLYX: { name: 'Polymesh' },
	AED: { name: 'UAE Dirham' },
	AFN: { name: 'Afghan Afghani' },
	ALL: { name: 'Albanian Lek' },
	AMD: { name: 'Armenian Dram' },
	ANG: { name: 'Netherlands Antillian Guilder' },
	AOA: { name: 'Angolan Kwanza' },
	ARS: { name: 'Argentine Peso' },
	AUD: { name: 'Australian Dollar' },
	AWG: { name: 'Aruban Florin' },
	AZN: { name: 'Azerbaijani Manat' },
	BAM: { name: 'Bosnia and Herzegovina Mark' },
	BBD: { name: 'Barbados Dollar' },
	BDT: { name: 'Bangladeshi Taka' },
	BGN: { name: 'Bulgarian Lev' },
	BHD: { name: 'Bahraini Dinar' },
	BIF: { name: 'Burundian Franc' },
	BMD: { name: 'Bermudian Dollar' },
	BND: { name: 'Brunei Dollar' },
	BOB: { name: 'Bolivian Boliviano' },
	BRL: { name: 'Brazilian Real' },
	BSD: { name: 'Bahamian Dollar' },
	BTN: { name: 'Bhutanese Ngultrum' },
	BWP: { name: 'Botswana Pula' },
	BYN: { name: 'Belarusian Ruble' },
	BZD: { name: 'Belize Dollar' },
	CAD: { name: 'Canadian Dollar' },
	CDF: { name: 'Congolese Franc' },
	CHF: { name: 'Swiss Franc' },
	CLP: { name: 'Chilean Peso' },
	CNY: { name: 'Chinese Renminbi' },
	COP: { name: 'Colombian Peso' },
	CRC: { name: 'Costa Rican Colon' },
	CUC: { name: 'Cuban Convertible Peso' },
	CUP: { name: 'Cuban Peso' },
	CVE: { name: 'Cape Verdean Escudo' },
	CZK: { name: 'Czech Koruna' },
	DJF: { name: 'Djiboutian Franc' },
	DKK: { name: 'Danish Krone' },
	DOP: { name: 'Dominican Peso' },
	DZD: { name: 'Algerian Dinar' },
	EGP: { name: 'Egyptian Pound' },
	ERN: { name: 'Eritrean Nakfa' },
	ETB: { name: 'Ethiopian Birr' },
	EUR: { name: 'Euro' },
	FJD: { name: 'Fiji Dollar' },
	FKP: { name: 'Falkland Islands Pound' },
	FOK: { name: 'Faroese Krona' },
	GBP: { name: 'Pound Sterling' },
	GEL: { name: 'Georgian Lari' },
	GGP: { name: 'Guernsey Pound' },
	GHS: { name: 'Ghanaian Cedi' },
	GIP: { name: 'Gibraltar Pound' },
	GMD: { name: 'Gambian Dalasi' },
	GNF: { name: 'Guinean Franc' },
	GTQ: { name: 'Guatemalan Quetzal' },
	GYD: { name: 'Guyanese Dollar' },
	HKD: { name: 'Hong Kong Dollar' },
	HNL: { name: 'Honduran Lempira' },
	HRK: { name: 'Croatian Kuna' },
	HTG: { name: 'Haitian Gourde' },
	HUF: { name: 'Hungarian Forint' },
	IDR: { name: 'Indonesian Rupiah' },
	ILS: { name: 'Israeli New Shekel' },
	IMP: { name: 'Manx Pound' },
	INR: { name: 'Indian Rupee' },
	IQD: { name: 'Iraqi Dinar' },
	IRR: { name: 'Iranian Rial' },
	ISK: { name: 'Icelandic Krona' },
	JMD: { name: 'Jamaican Dollar' },
	JOD: { name: 'Jordanian Dinar' },
	JPY: { name: 'Japanese Yen' },
	KES: { name: 'Kenyan Shilling' },
	KGS: { name: 'Kyrgyzstani Som' },
	KHR: { name: 'Cambodian Riel' },
	KID: { name: 'Kiribati Dollar' },
	KMF: { name: 'Comorian Franc' },
	KRW: { name: 'South Korean Won' },
	KWD: { name: 'Kuwaiti Dinar' },
	KYD: { name: 'Cayman Islands Dollar' },
	KZT: { name: 'Kazakhstani Tenge' },
	LAK: { name: 'Lao Kip' },
	LBP: { name: 'Lebanese Pound' },
	LKR: { name: 'Sri Lanka Rupee' },
	LRD: { name: 'Liberian Dollar' },
	LSL: { name: 'Lesotho Loti' },
	LYD: { name: 'Libyan Dinar' },
	MAD: { name: 'Moroccan Dirham' },
	MDL: { name: 'Moldovan Leu' },
	MGA: { name: 'Malagasy Ariary' },
	MKD: { name: 'Macedonian Denar' },
	MMK: { name: 'Burmese Kyat' },
	MNT: { name: 'Mongolian Togrog' },
	MOP: { name: 'Macanese Pataca' },
	MRU: { name: 'Mauritanian Ouguiya' },
	MUR: { name: 'Mauritian Rupee' },
	MVR: { name: 'Maldivian Rufiyaa' },
	MWK: { name: 'Malawian Kwacha' },
	MXN: { name: 'Mexican Peso' },
	MYR: { name: 'Malaysian Ringgit' },
	MZN: { name: 'Mozambican Metical' },
	NAD: { name: 'Namibian Dollar' },
	NGN: { name: 'Nigerian Naira' },
	NIO: { name: 'Nicaraguan Cordoba' },
	NOK: { name: 'Norwegian Krone' },
	NPR: { name: 'Nepalese Rupee' },
	NZD: { name: 'New Zealand Dollar' },
	OMR: { name: 'Omani Rial' },
	PAB: { name: 'Panamanian Balboa' },
	PEN: { name: 'Peruvian Sol' },
	PGK: { name: 'Papua New Guinean Kina' },
	PHP: { name: 'Philippine Peso' },
	PKR: { name: 'Pakistani Rupee' },
	PLN: { name: 'Polish Zloty' },
	PYG: { name: 'Paraguayan Guarani' },
	QAR: { name: 'Qatari Riyal' },
	RON: { name: 'Romanian Leu' },
	RSD: { name: 'Serbian Dinar' },
	RUB: { name: 'Russian Ruble' },
	RWF: { name: 'Rwandan Franc' },
	SAR: { name: 'Saudi Riyal' },
	SBD: { name: 'Solomon Islands Dollar' },
	SCR: { name: 'Seychellois Rupee' },
	SDG: { name: 'Sudanese Pound' },
	SEK: { name: 'Swedish Krona' },
	SGD: { name: 'Singapore Dollar' },
	SHP: { name: 'Saint Helena Pound' },
	SLL: { name: 'Sierra Leonean Leone' },
	SOS: { name: 'Somali Shilling' },
	SRD: { name: 'Surinamese Dollar' },
	SSP: { name: 'South Sudanese Pound' },
	STN: { name: 'Sao Tome and Principe Dobra' },
	SYP: { name: 'Syrian Pound' },
	SZL: { name: 'Eswatini Lilangeni' },
	THB: { name: 'Thai Baht' },
	TJS: { name: 'Tajikistani Somoni' },
	TMT: { name: 'Turkmenistan Manat' },
	TND: { name: 'Tunisian Dinar' },
	TOP: { name: 'Tongan Pa\'anga' },
	TRY: { name: 'Turkish Lira' },
	TTD: { name: 'Trinidad and Tobago Dollar' },
	TVD: { name: 'Tuvaluan Dollar' },
	TWD: { name: 'New Taiwan Dollar' },
	TZS: { name: 'Tanzanian Shilling' },
	UAH: { name: 'Ukrainian Hryvnia' },
	UGX: { name: 'Ugandan Shilling' },
	USD: { name: 'United States Dollar' },
	UYU: { name: 'Uruguayan Peso' },
	UZS: { name: 'Uzbekistani So\'m' },
	VES: { name: 'Venezuelan Bolivar Soberano' },
	VND: { name: 'Vietnamese Dong' },
	VUV: { name: 'Vanuatu Vatu' },
	WST: { name: 'Samoan Tala' },
	XAF: { name: 'Central African CFA Franc' },
	XCD: { name: 'East Caribbean Dollar' },
	XDR: { name: 'Special Drawing Rights' },
	XOF: { name: 'West African CFA franc' },
	XPF: { name: 'CFP Franc' },
	YER: { name: 'Yemeni Rial' },
	ZAR: { name: 'South African Rand' },
	ZMW: { name: 'Zambian Kwacha' }
}
