var icon_style = 'material-outlined'
var icon_size = 16
var icon_color = '40C057'
var default_icon_url = `https://img.icons8.com/${icon_style}/${icon_size}/${icon_color}/`

var dollar = default_icon_url + 'us-dollar--v1.png'
var peso = default_icon_url + 'peso-symbol.png'
var rupee = default_icon_url + 'peso-symbol.png'
var krona = default_icon_url + 'swedish-krona.png'
var franc = default_icon_url + 'swiss-franc.png'
var pound = default_icon_url + 'british-pound.png'
var currenciesJSON =
{
	'BTC': { name: 'Bitcoin', image: 'https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png' },
	'ETH': { name: 'Ethereum', image: 'https://assets.coingecko.com/coins/images/279/thumb/ethereum.png' },
	'USDT': { name: 'Tether', image: 'https://assets.coingecko.com/coins/images/325/thumb/Tether.png' },
	'BNB': { name: 'BNB', image: 'https://assets.coingecko.com/coins/images/825/thumb/bnb-icon2_2x.png' },
	'USDC': { name: 'USD Coin', image: 'https://assets.coingecko.com/coins/images/6319/thumb/USD_Coin_icon.png' },
	'XRP': { name: 'XRP', image: 'https://assets.coingecko.com/coins/images/44/thumb/xrp-symbol-white-128.png' },
	'ADA': { name: 'Cardano', image: 'https://assets.coingecko.com/coins/images/975/thumb/cardano.png' },
	'STETH': { name: 'Lido Staked Ether', image: 'https://assets.coingecko.com/coins/images/13442/thumb/steth_logo.png' },
	'DOGE': { name: 'Dogecoin', image: 'https://assets.coingecko.com/coins/images/5/thumb/dogecoin.png' },
	'MATIC': { name: 'Polygon', image: 'https://assets.coingecko.com/coins/images/4713/thumb/matic-token-icon.png' },
	'SOL': { name: 'Solana', image: 'https://assets.coingecko.com/coins/images/4128/thumb/solana.png' },
	'BUSD': { name: 'Binance USD', image: 'https://assets.coingecko.com/coins/images/9576/thumb/BUSD.png' },
	'DOT': { name: 'Polkadot', image: 'https://assets.coingecko.com/coins/images/12171/thumb/polkadot.png' },
	'LTC': { name: 'Litecoin', image: 'https://assets.coingecko.com/coins/images/2/thumb/litecoin.png' },
	'SHIB': { name: 'Shiba Inu', image: 'https://assets.coingecko.com/coins/images/11939/thumb/shiba.png' },
	'TRX': { name: 'TRON', image: 'https://assets.coingecko.com/coins/images/1094/thumb/tron-logo.png' },
	'AVAX': { name: 'Avalanche', image: 'https://assets.coingecko.com/coins/images/12559/thumb/Avalanche_Circle_RedWhite_Trans.png' },
	'DAI': { name: 'Dai', image: 'https://assets.coingecko.com/coins/images/9956/thumb/4943.png' },
	'UNI': { name: 'Uniswap', image: 'https://assets.coingecko.com/coins/images/12504/thumb/uniswap-uni.png' },
	'WBTC': { name: 'Wrapped Bitcoin', image: 'https://assets.coingecko.com/coins/images/7598/thumb/wrapped_bitcoin_wbtc.png' },
	'LINK': { name: 'Chainlink', image: 'https://assets.coingecko.com/coins/images/877/thumb/chainlink-new-logo.png' },
	'ATOM': { name: 'Cosmos Hub', image: 'https://assets.coingecko.com/coins/images/1481/thumb/cosmos_hub.png' },
	'LEO': { name: 'LEO Token', image: 'https://assets.coingecko.com/coins/images/8418/thumb/leo-token.png' },
	'TON': { name: 'Toncoin', image: 'https://assets.coingecko.com/coins/images/17980/thumb/ton_symbol.png' },
	'XMR': { name: 'Monero', image: 'https://assets.coingecko.com/coins/images/69/thumb/monero_logo.png' },
	'ETC': { name: 'Ethereum Classic', image: 'https://assets.coingecko.com/coins/images/453/thumb/ethereum-classic-logo.png' },
	'XLM': { name: 'Stellar', image: 'https://assets.coingecko.com/coins/images/100/thumb/Stellar_symbol_black_RGB.png' },
	'OKB': { name: 'OKB', image: 'https://assets.coingecko.com/coins/images/4463/thumb/WeChat_Image_20220118095654.png' },
	'BCH': { name: 'Bitcoin Cash', image: 'https://assets.coingecko.com/coins/images/780/thumb/bitcoin-cash-circle.png' },
	'FIL': { name: 'Filecoin', image: 'https://assets.coingecko.com/coins/images/12817/thumb/filecoin.png' },
	'TUSD': { name: 'TrueUSD', image: 'https://assets.coingecko.com/coins/images/3449/thumb/tusd.png' },
	'APT': { name: 'Aptos', image: 'https://assets.coingecko.com/coins/images/26455/thumb/aptos_round.png' },
	'LDO': { name: 'Lido DAO', image: 'https://assets.coingecko.com/coins/images/13573/thumb/Lido_DAO.png' },
	'HBAR': { name: 'Hedera', image: 'https://assets.coingecko.com/coins/images/3688/thumb/hbar.png' },
	'QNT': { name: 'Quant', image: 'https://assets.coingecko.com/coins/images/3370/thumb/5ZOu7brX_400x400.jpg' },
	'ARB': { name: 'Arbitrum', image: 'https://assets.coingecko.com/coins/images/16547/thumb/photo_2023-03-29_21.47.00.jpeg' },
	'CRO': { name: 'Cronos', image: 'https://assets.coingecko.com/coins/images/7310/thumb/cro_token_logo.png' },
	'NEAR': { name: 'NEAR Protocol', image: 'https://assets.coingecko.com/coins/images/10365/thumb/near.png' },
	'VET': { name: 'VeChain', image: 'https://assets.coingecko.com/coins/images/1167/thumb/VET_Token_Icon.png' },
	'ALGO': { name: 'Algorand', image: 'https://assets.coingecko.com/coins/images/4380/thumb/download.png' },
	'APE': { name: 'ApeCoin', image: 'https://assets.coingecko.com/coins/images/24383/thumb/apecoin.jpg' },
	'ICP': { name: 'Internet Computer', image: 'https://assets.coingecko.com/coins/images/14495/thumb/Internet_Computer_logo.png' },
	'STX': { name: 'Stacks', image: 'https://assets.coingecko.com/coins/images/2069/thumb/Stacks_logo_full.png' },
	'GRT': { name: 'The Graph', image: 'https://assets.coingecko.com/coins/images/13397/thumb/Graph_Token.png' },
	'EOS': { name: 'EOS', image: 'https://assets.coingecko.com/coins/images/738/thumb/eos-eos-logo.png' },
	'FTM': { name: 'Fantom', image: 'https://assets.coingecko.com/coins/images/4001/thumb/Fantom_round.png' },
	'SAND': { name: 'The Sandbox', image: 'https://assets.coingecko.com/coins/images/12129/thumb/sandbox_logo.jpg' },
	'EGLD': { name: 'MultiversX', image: 'https://assets.coingecko.com/coins/images/12335/thumb/egld-token-logo.png' },
	'MANA': { name: 'Decentraland', image: 'https://assets.coingecko.com/coins/images/878/thumb/decentraland-mana.png' },
	'FRAX': { name: 'Frax', image: 'https://assets.coingecko.com/coins/images/13422/thumb/FRAX_icon.png' },
	'AAVE': { name: 'Aave', image: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png' },
	'IMX': { name: 'ImmutableX', image: 'https://assets.coingecko.com/coins/images/17233/thumb/immutableX-symbol-BLK-RGB.png' },
	'XTZ': { name: 'Tezos', image: 'https://assets.coingecko.com/coins/images/976/thumb/Tezos-logo.png' },
	'THETA': { name: 'Theta Network', image: 'https://assets.coingecko.com/coins/images/2538/thumb/theta-token-logo.png' },
	'FLOW': { name: 'Flow', image: 'https://assets.coingecko.com/coins/images/13446/thumb/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png' },
	'AXS': { name: 'Axie Infinity', image: 'https://assets.coingecko.com/coins/images/13029/thumb/axie_infinity_logo.png' },
	'EDGT': { name: 'Edgecoin', image: 'https://assets.coingecko.com/coins/images/14409/thumb/edgecoin_bank_logo-4_%281%29.png' },
	'CFX': { name: 'Conflux', image: 'https://assets.coingecko.com/coins/images/13079/thumb/3vuYMbjN.png' },
	'NEO': { name: 'NEO', image: 'https://assets.coingecko.com/coins/images/480/thumb/NEO_512_512.png' },
	'RPL': { name: 'Rocket Pool', image: 'https://assets.coingecko.com/coins/images/2090/thumb/rocket_pool_%28RPL%29.png' },
	'KCS': { name: 'KuCoin', image: 'https://assets.coingecko.com/coins/images/1047/thumb/sa9z79.png' },
	'SNX': { name: 'Synthetix Network', image: 'https://assets.coingecko.com/coins/images/3406/thumb/SNX.png' },
	'WBT': { name: 'WhiteBIT Token', image: 'https://assets.coingecko.com/coins/images/27045/thumb/wbt_token.png' },
	'USDP': { name: 'Pax Dollar', image: 'https://assets.coingecko.com/coins/images/6013/thumb/Pax_Dollar.png' },
	'BIT': { name: 'BitDAO', image: 'https://assets.coingecko.com/coins/images/17627/thumb/rI_YptK8.png' },
	'CRV': { name: 'Curve DAO', image: 'https://assets.coingecko.com/coins/images/12124/thumb/Curve.png' },
	'LUNC': { name: 'Terra Luna Classic', image: 'https://assets.coingecko.com/coins/images/8284/thumb/01_LunaClassic_color.png' },
	'USDD': { name: 'USDD', image: 'https://assets.coingecko.com/coins/images/25380/thumb/UUSD.jpg' },
	'KLAY': { name: 'Klaytn', image: 'https://assets.coingecko.com/coins/images/9672/thumb/klaytn.png' },
	'OP': { name: 'Optimism', image: 'https://assets.coingecko.com/coins/images/25244/thumb/Optimism.png' },
	'GT': { name: 'Gate', image: 'https://assets.coingecko.com/coins/images/8183/thumb/gt.png' },
	'BSV': { name: 'Bitcoin SV', image: 'https://assets.coingecko.com/coins/images/6799/thumb/BSV.png' },
	'CAKE': { name: 'PancakeSwap', image: 'https://assets.coingecko.com/coins/images/12632/thumb/pancakeswap-cake-logo_%281%29.png' },
	'MINA': { name: 'Mina Protocol', image: 'https://assets.coingecko.com/coins/images/15628/thumb/JM4_vQ34_400x400.png' },
	'GMX': { name: 'GMX', image: 'https://assets.coingecko.com/coins/images/18323/thumb/arbit.png' },
	'DASH': { name: 'Dash', image: 'https://assets.coingecko.com/coins/images/19/thumb/dash-logo.png' },
	'CHZ': { name: 'Chiliz', image: 'https://assets.coingecko.com/coins/images/8834/thumb/CHZ_Token_updated.png' },
	'MKR': { name: 'Maker', image: 'https://assets.coingecko.com/coins/images/1364/thumb/Mark_Maker.png' },
	'FXS': { name: 'Frax Share', image: 'https://assets.coingecko.com/coins/images/13423/thumb/Frax_Shares_icon.png' },
	'HT': { name: 'Huobi', image: 'https://assets.coingecko.com/coins/images/2822/thumb/huobi-token-logo.png' },
	'XEC': { name: 'eCash', image: 'https://assets.coingecko.com/coins/images/16646/thumb/Logo_final-22.png' },
	'BTT': { name: 'BitTorrent', image: 'https://assets.coingecko.com/coins/images/22457/thumb/btt_logo.png' },
	'MIOTA': { name: 'IOTA', image: 'https://assets.coingecko.com/coins/images/692/thumb/IOTA_Swirl.png' },
	'XDC': { name: 'XDC Network', image: 'https://assets.coingecko.com/coins/images/2912/thumb/xdc-icon.png' },
	'BGB': { name: 'Bitget Token', image: 'https://assets.coingecko.com/coins/images/11610/thumb/photo_2022-01-24_14-08-03.jpg' },
	'CUSDC': { name: 'cUSDC', image: 'https://assets.coingecko.com/coins/images/9442/thumb/Compound_USDC.png' },
	'KAS': { name: 'Kaspa', image: 'https://assets.coingecko.com/coins/images/25751/thumb/kaspa-icon-exchanges.png' },
	'CETH': { name: 'cETH', image: 'https://assets.coingecko.com/coins/images/10643/thumb/ceth2.JPG' },
	'PAXG': { name: 'PAX Gold', image: 'https://assets.coingecko.com/coins/images/9519/thumb/paxg.PNG' },
	'TKX': { name: 'Tokenize Xchange', image: 'https://assets.coingecko.com/coins/images/4984/thumb/TKX_-_Logo_-_RGB-15.png' },
	'AGIX': { name: 'SingularityNET', image: 'https://assets.coingecko.com/coins/images/2138/thumb/singularitynet.png' },
	'TWT': { name: 'Trust Wallet', image: 'https://assets.coingecko.com/coins/images/11085/thumb/Trust.png' },
	'1INCH': { name: '1inch', image: 'https://assets.coingecko.com/coins/images/13469/thumb/1inch-token.png' },
	'XAUT': { name: 'Tether Gold', image: 'https://assets.coingecko.com/coins/images/10481/thumb/Tether_Gold.png' },
	'MASK': { name: 'Mask Network', image: 'https://assets.coingecko.com/coins/images/14051/thumb/Mask_Network.jpg' },
	'FLR': { name: 'Flare', image: 'https://assets.coingecko.com/coins/images/28624/thumb/FLR-icon200x200.png' },
	'RNDR': { name: 'Render', image: 'https://assets.coingecko.com/coins/images/11636/thumb/rndr.png' },
	'ZIL': { name: 'Zilliqa', image: 'https://assets.coingecko.com/coins/images/2687/thumb/Zilliqa-logo.png' },
	'LRC': { name: 'Loopring', image: 'https://assets.coingecko.com/coins/images/913/thumb/LRC.png' },
	'OSMO': { name: 'Osmosis', image: 'https://assets.coingecko.com/coins/images/16724/thumb/osmo.png' },
	'XRD': { name: 'Radix', image: 'https://assets.coingecko.com/coins/images/4374/thumb/Radix.png' },
	'RUNE': { name: 'THORChain', image: 'https://assets.coingecko.com/coins/images/6595/thumb/Rune200x200.png' },
	'RETH': { name: 'Rocket Pool ETH', image: 'https://assets.coingecko.com/coins/images/20764/thumb/reth.png' },
	'NEXO': { name: 'NEXO', image: 'https://assets.coingecko.com/coins/images/3695/thumb/nexo.png' },
	'KAVA': { name: 'Kava', image: 'https://assets.coingecko.com/coins/images/9761/thumb/kava.png' },
	'AR': { name: 'Arweave', image: 'https://assets.coingecko.com/coins/images/4343/thumb/oRt6SiEN_400x400.jpg' },
	'CVX': { name: 'Convex Finance', image: 'https://assets.coingecko.com/coins/images/15585/thumb/convex.png' },
	'CSPR': { name: 'Casper Network', image: 'https://assets.coingecko.com/coins/images/15279/thumb/casper.PNG' },
	'ZEC': { name: 'Zcash', image: 'https://assets.coingecko.com/coins/images/486/thumb/circle-zcash-color.png' },
	'ENJ': { name: 'Enjin Coin', image: 'https://assets.coingecko.com/coins/images/1102/thumb/enjin-coin-logo.png' },
	'GUSD': { name: 'Gemini Dollar', image: 'https://assets.coingecko.com/coins/images/5992/thumb/gemini-dollar-gusd.png' },
	'CDAI': { name: 'cDAI', image: 'https://assets.coingecko.com/coins/images/9281/thumb/cDAI.png' },
	'OKT': { name: 'OKT Chain', image: 'https://assets.coingecko.com/coins/images/13708/thumb/WeChat_Image_20220118095654.png' },
	'FET': { name: 'Fetch.ai', image: 'https://assets.coingecko.com/coins/images/5681/thumb/Fetch.jpg' },
	'BTSE': { name: 'BTSE Token', image: 'https://assets.coingecko.com/coins/images/10807/thumb/BTSE_logo_Square.jpeg' },
	'DYDX': { name: 'dYdX', image: 'https://assets.coingecko.com/coins/images/17500/thumb/hjnIm9bV.jpg' },
	'DFI': { name: 'DeFiChain', image: 'https://assets.coingecko.com/coins/images/11757/thumb/symbol-defi-blockchain_200.png' },
	'ETHW': { name: 'EthereumPoW', image: 'https://assets.coingecko.com/coins/images/26997/thumb/logo-clear.png' },
	'BAT': { name: 'Basic Attention', image: 'https://assets.coingecko.com/coins/images/677/thumb/basic-attention-token.png' },
	'BABYDOGE': { name: 'Baby Doge Coin', image: 'https://assets.coingecko.com/coins/images/16125/thumb/babydoge.jpg' },
	'WEMIX': { name: 'WEMIX', image: 'https://assets.coingecko.com/coins/images/12998/thumb/wemixcoin_color_200.png' },
	'XEM': { name: 'NEM', image: 'https://assets.coingecko.com/coins/images/242/thumb/NEM_WC_Logo_200px.png' },
	'WOO': { name: 'WOO Network', image: 'https://assets.coingecko.com/coins/images/12921/thumb/w2UiemF__400x400.jpg' },
	'INJ': { name: 'Injective', image: 'https://assets.coingecko.com/coins/images/12882/thumb/Secondary_Symbol.png' },
	'AZERO': { name: 'Aleph Zero', image: 'https://assets.coingecko.com/coins/images/17212/thumb/gtmuTVa.png' },
	'ENS': { name: 'Ethereum Name Service', image: 'https://assets.coingecko.com/coins/images/19785/thumb/acatxTm8_400x400.jpg' },
	'NXM': { name: 'Nexus Mutual', image: 'https://assets.coingecko.com/coins/images/11810/thumb/NXMmain.png' },
	'FLOKI': { name: 'FLOKI', image: 'https://assets.coingecko.com/coins/images/16746/thumb/PNG_image.png' },
	'CELO': { name: 'Celo', image: 'https://assets.coingecko.com/coins/images/11090/thumb/InjXBNx9_400x400.jpg' },
	'HOT': { name: 'Holo', image: 'https://assets.coingecko.com/coins/images/3348/thumb/Holologo_Profile.png' },
	'TFUEL': { name: 'Theta Fuel', image: 'https://assets.coingecko.com/coins/images/8029/thumb/1_0YusgngOrriVg4ZYx4wOFQ.png' },
	'QTUM': { name: 'Qtum', image: 'https://assets.coingecko.com/coins/images/684/thumb/Qtum_Logo_blue_CG.png' },
	'LUNA': { name: 'Terra', image: 'https://assets.coingecko.com/coins/images/25767/thumb/01_Luna_color.png' },
	'BDX': { name: 'Beldex', image: 'https://assets.coingecko.com/coins/images/5111/thumb/Beldex.png' },
	'GALA': { name: 'GALA', image: 'https://assets.coingecko.com/coins/images/12493/thumb/GALA-COINGECKO.png' },
	'KSM': { name: 'Kusama', image: 'https://assets.coingecko.com/coins/images/9568/thumb/m4zRhP5e_400x400.jpg' },
	'DCR': { name: 'Decred', image: 'https://assets.coingecko.com/coins/images/329/thumb/decred.png' },
	'RVN': { name: 'Ravencoin', image: 'https://assets.coingecko.com/coins/images/3412/thumb/ravencoin.png' },
	'COMP': { name: 'Compound', image: 'https://assets.coingecko.com/coins/images/10775/thumb/COMP.png' },
	'MAGIC': { name: 'Magic', image: 'https://assets.coingecko.com/coins/images/18623/thumb/magic.png' },
	'YFI': { name: 'yearn.finance', image: 'https://assets.coingecko.com/coins/images/11849/thumb/yearn-finance-yfi.png' },
	'GNO': { name: 'Gnosis', image: 'https://assets.coingecko.com/coins/images/662/thumb/logo_square_simple_300px.png' },
	'ROSE': { name: 'Oasis Network', image: 'https://assets.coingecko.com/coins/images/13162/thumb/rose.png' },
	'OHM': { name: 'Olympus', image: 'https://assets.coingecko.com/coins/images/14483/thumb/token_OHM_%281%29.png' },
	'LN': { name: 'LINK', image: 'https://assets.coingecko.com/coins/images/6450/thumb/linklogo.png' },
	'FLEX': { name: 'FLEX Coin', image: 'https://assets.coingecko.com/coins/images/9108/thumb/coinflex_logo.png' },
	'BTG': { name: 'Bitcoin Gold', image: 'https://assets.coingecko.com/coins/images/1043/thumb/bitcoin-gold-logo.png' },
	'AUDIO': { name: 'Audius', image: 'https://assets.coingecko.com/coins/images/12913/thumb/AudiusCoinLogo_2x.png' },
	'GFARM2': { name: 'Gains Farm', image: 'https://assets.coingecko.com/coins/images/13703/thumb/gfarm_v2.png' },
	'SAFEMOON': { name: 'SafeMoon [OLD]', image: 'https://assets.coingecko.com/coins/images/14362/thumb/174x174-white.png' },
	'BAL': { name: 'Balancer', image: 'https://assets.coingecko.com/coins/images/11683/thumb/Balancer.png' },
	'ASTR': { name: 'Astar', image: 'https://assets.coingecko.com/coins/images/22617/thumb/astr.png' },
	'LUSD': { name: 'Liquity USD', image: 'https://assets.coingecko.com/coins/images/14666/thumb/Group_3.png' },
	'XCH': { name: 'Chia', image: 'https://assets.coingecko.com/coins/images/15174/thumb/zV5K5y9f_400x400.png' },
	'ANKR': { name: 'Ankr Network', image: 'https://assets.coingecko.com/coins/images/4324/thumb/U85xTl2.png' },
	'SSV': { name: 'SSV Network', image: 'https://assets.coingecko.com/coins/images/19155/thumb/ssv.png' },
	'SXP': { name: 'SXP', image: 'https://assets.coingecko.com/coins/images/9368/thumb/swipe.png' },
	'HBTC': { name: 'Huobi BTC', image: 'https://assets.coingecko.com/coins/images/12407/thumb/Unknown-5.png' },
	'ONE': { name: 'Harmony', image: 'https://assets.coingecko.com/coins/images/4344/thumb/Y88JAze.png' },
	'BONE': { name: 'Bone ShibaSwap', image: 'https://assets.coingecko.com/coins/images/16916/thumb/bone_icon.png' },
	'GMT': { name: 'STEPN', image: 'https://assets.coingecko.com/coins/images/23597/thumb/gmt.png' },
	'ASTRAFER': { name: 'Astrafer', image: 'https://assets.coingecko.com/coins/images/26246/thumb/ATSRA_Token.png' },
	'IOTX': { name: 'IoTeX', image: 'https://assets.coingecko.com/coins/images/3334/thumb/iotex-logo.png' },
	'ACS': { name: 'Access Protocol', image: 'https://assets.coingecko.com/coins/images/28747/thumb/dR4FovX4_400x400.jpg' },
	'GLM': { name: 'Golem', image: 'https://assets.coingecko.com/coins/images/542/thumb/Golem_Submark_Positive_RGB.png' },
	'CVXCRV': { name: 'Convex CRV', image: 'https://assets.coingecko.com/coins/images/15586/thumb/convex-crv.png' },
	'CUSDT': { name: 'cUSDT', image: 'https://assets.coingecko.com/coins/images/11621/thumb/cUSDT.png' },
	'DAO': { name: 'DAO Maker', image: 'https://assets.coingecko.com/coins/images/13915/thumb/4.png' },
	'JST': { name: 'JUST', image: 'https://assets.coingecko.com/coins/images/11095/thumb/JUST.jpg' },
	'GNS': { name: 'Gains Network', image: 'https://assets.coingecko.com/coins/images/19737/thumb/logo.png' },
	'JASMY': { name: 'JasmyCoin', image: 'https://assets.coingecko.com/coins/images/13876/thumb/JASMY200x200.jpg' },
	'NU': { name: 'NuCypher', image: 'https://assets.coingecko.com/coins/images/3318/thumb/photo1198982838879365035.jpg' },
	'FRXETH': { name: 'Frax Ether', image: 'https://assets.coingecko.com/coins/images/28284/thumb/frxETH_icon.png' },
	'BAND': { name: 'Band Protocol', image: 'https://assets.coingecko.com/coins/images/9545/thumb/Band_token_blue_violet_token.png' },
	'ELG': { name: 'Escoin', image: 'https://assets.coingecko.com/coins/images/13566/thumb/escoin-200.png' },
	'KDA': { name: 'Kadena', image: 'https://assets.coingecko.com/coins/images/3693/thumb/djLWD6mR_400x400.jpg' },
	'GLMR': { name: 'Moonbeam', image: 'https://assets.coingecko.com/coins/images/22459/thumb/glmr.png' },
	'OMG': { name: 'OMG Network', image: 'https://assets.coingecko.com/coins/images/776/thumb/OMG_Network.jpg' },
	'EURT': { name: 'Euro Tether', image: 'https://assets.coingecko.com/coins/images/17385/thumb/Tether_full_logo_dm.png' },
	'CDT': { name: 'Blox', image: 'https://assets.coingecko.com/coins/images/1231/thumb/Blox_Staking_Logo_2.png' },
	'BLUR': { name: 'Blur', image: 'https://assets.coingecko.com/coins/images/28453/thumb/blur.png' },
	'WAVES': { name: 'Waves', image: 'https://assets.coingecko.com/coins/images/425/thumb/waves.png' },
	'SURE': { name: 'inSure DeFi', image: 'https://assets.coingecko.com/coins/images/10354/thumb/logo-grey-circle.png' },
	'ICX': { name: 'ICON', image: 'https://assets.coingecko.com/coins/images/1060/thumb/icon-icx-logo.png' },
	'USTC': { name: 'TerraClassicUSD', image: 'https://assets.coingecko.com/coins/images/12681/thumb/UST.png' },
	'AMP': { name: 'Amp', image: 'https://assets.coingecko.com/coins/images/12409/thumb/amp-200x200.png' },
	'SUSHI': { name: 'Sushi', image: 'https://assets.coingecko.com/coins/images/12271/thumb/512x512_Logo_no_chop.png' },
	'SC': { name: 'Siacoin', image: 'https://assets.coingecko.com/coins/images/289/thumb/siacoin.png' },
	'ONT': { name: 'Ontology', image: 'https://assets.coingecko.com/coins/images/3447/thumb/ONT.png' },
	'JOE': { name: 'JOE', image: 'https://assets.coingecko.com/coins/images/17569/thumb/joe_200x200.png' },
	'BTC.B': { name: 'Bitcoin Avalanche Bridged (BTC.b)', image: 'https://assets.coingecko.com/coins/images/26115/thumb/btcb.png' },
	'ECOIN': { name: 'Ecoin', image: 'https://assets.coingecko.com/coins/images/10849/thumb/IMG_4307.jpg' },
	'ZRX': { name: '0x', image: 'https://assets.coingecko.com/coins/images/863/thumb/0x.png' },
	'OMI': { name: 'ECOMI', image: 'https://assets.coingecko.com/coins/images/4428/thumb/ECOMI.png' },
	'LQTY': { name: 'Liquity', image: 'https://assets.coingecko.com/coins/images/14665/thumb/200-lqty-icon.png' },
	'HNT': { name: 'Helium', image: 'https://assets.coingecko.com/coins/images/4284/thumb/Helium_HNT.png' },
	'MX': { name: 'MX', image: 'https://assets.coingecko.com/coins/images/8545/thumb/MEXC_GLOBAL_LOGO.jpeg' },
	'IOST': { name: 'IOST', image: 'https://assets.coingecko.com/coins/images/2523/thumb/IOST.png' },
	'BICO': { name: 'Biconomy', image: 'https://assets.coingecko.com/coins/images/21061/thumb/biconomy_logo.jpg' },
	'ELON': { name: 'Dogelon Mars', image: 'https://assets.coingecko.com/coins/images/14962/thumb/6GxcPRo3_400x400.jpg' },
	'LPT': { name: 'Livepeer', image: 'https://assets.coingecko.com/coins/images/7137/thumb/logo-circle-green.png' },
	'BRISE': { name: 'Bitgert', image: 'https://assets.coingecko.com/coins/images/17388/thumb/bitgert.png' },
	'FLUX': { name: 'Flux', image: 'https://assets.coingecko.com/coins/images/5163/thumb/Flux_symbol_blue-white.png' },
	'RSR': { name: 'Reserve Rights', image: 'https://assets.coingecko.com/coins/images/8365/thumb/rsr.png' },
	'BLID': { name: 'Bolide', image: 'https://assets.coingecko.com/coins/images/25548/thumb/BLID_token_logo_200x200.png' },
	'ACH': { name: 'Alchemy Pay', image: 'https://assets.coingecko.com/coins/images/12390/thumb/ACH_%281%29.png' },
	'MULTI': { name: 'Multichain', image: 'https://assets.coingecko.com/coins/images/22087/thumb/1_Wyot-SDGZuxbjdkaOeT2-A.png' },
	'SFP': { name: 'SafePal', image: 'https://assets.coingecko.com/coins/images/13905/thumb/sfp.png' },
	'EVMOS': { name: 'Evmos', image: 'https://assets.coingecko.com/coins/images/24023/thumb/evmos.png' },
	'SYN': { name: 'Synapse', image: 'https://assets.coingecko.com/coins/images/18024/thumb/synapse_social_icon.png' },
	'RON': { name: 'Ronin', image: 'https://assets.coingecko.com/coins/images/20009/thumb/ronin.jpg' },
	'ALUSD': { name: 'Alchemix USD', image: 'https://assets.coingecko.com/coins/images/14114/thumb/Alchemix_USD.png' },
	'CHSB': { name: 'SwissBorg', image: 'https://assets.coingecko.com/coins/images/2117/thumb/YJUrRy7r_400x400.png' },
	'BORA': { name: 'BORA', image: 'https://assets.coingecko.com/coins/images/7646/thumb/mqFw8hxm_400x400.jpeg' },
	'SKL': { name: 'SKALE', image: 'https://assets.coingecko.com/coins/images/13245/thumb/SKALE_token_300x300.png' },
	'WAXP': { name: 'WAX', image: 'https://assets.coingecko.com/coins/images/1372/thumb/WAX_Coin_Tickers_P_512px.png' },
	'CKB': { name: 'Nervos Network', image: 'https://assets.coingecko.com/coins/images/9566/thumb/Nervos_White.png' },
	'TEL': { name: 'Telcoin', image: 'https://assets.coingecko.com/coins/images/1899/thumb/tel.png' },
	'HIVE': { name: 'Hive', image: 'https://assets.coingecko.com/coins/images/10840/thumb/logo_transparent_4x.png' },
	'POLY': { name: 'Polymath', image: 'https://assets.coingecko.com/coins/images/2784/thumb/inKkF01.png' },
	'KUB': { name: 'Bitkub Coin', image: 'https://assets.coingecko.com/coins/images/15760/thumb/KUB.png' },
	'DGB': { name: 'DigiByte', image: 'https://assets.coingecko.com/coins/images/63/thumb/digibyte.png' },
	'EWT': { name: 'Energy Web', image: 'https://assets.coingecko.com/coins/images/10886/thumb/R9gQTJV__400x400.png' },
	'OCEAN': { name: 'Ocean Protocol', image: 'https://assets.coingecko.com/coins/images/3687/thumb/ocean-protocol-logo.jpg' },
	'LSK': { name: 'Lisk', image: 'https://assets.coingecko.com/coins/images/385/thumb/Lisk_Symbol_-_Blue.png' },
	'RBN': { name: 'Ribbon Finance', image: 'https://assets.coingecko.com/coins/images/15823/thumb/RBN_64x64.png' },
	'UMA': { name: 'UMA', image: 'https://assets.coingecko.com/coins/images/10951/thumb/UMA.png' },
	'ILV': { name: 'Illuvium', image: 'https://assets.coingecko.com/coins/images/14468/thumb/ILV.JPG' },
	'ZEN': { name: 'Horizen', image: 'https://assets.coingecko.com/coins/images/691/thumb/horizen.png' },
	'CEL': { name: 'Celsius Network', image: 'https://assets.coingecko.com/coins/images/3263/thumb/CEL_logo.png' },
	'ID': { name: 'SPACE ID', image: 'https://assets.coingecko.com/coins/images/29468/thumb/sid_token_logo_%28green2%29.png' },
	'SFRXETH': { name: 'Staked Frax Ether', image: 'https://assets.coingecko.com/coins/images/28285/thumb/sfrxETH_icon.png' },
	'FUC': { name: 'FUBT Token', image: 'https://assets.coingecko.com/coins/images/8132/thumb/FUC_fubt_token.png' },
	'TRAC': { name: 'OriginTrail', image: 'https://assets.coingecko.com/coins/images/1877/thumb/TRAC.jpg' },
	'ELF': { name: 'aelf', image: 'https://assets.coingecko.com/coins/images/1371/thumb/aelf-logo.png' },
	'RIF': { name: 'RSK Infrastructure Framework', image: 'https://assets.coingecko.com/coins/images/7460/thumb/RIF.png' },
	'DAG': { name: 'Constellation', image: 'https://assets.coingecko.com/coins/images/4645/thumb/Constellation_Network_Logo.png' },
	'SETH2': { name: 'sETH2', image: 'https://assets.coingecko.com/coins/images/16569/thumb/emerald256.png' },
	'EVER': { name: 'Everscale', image: 'https://assets.coingecko.com/coins/images/12783/thumb/everscale_badge_main_round_1x.png' },
	'EURS': { name: 'STASIS EURO', image: 'https://assets.coingecko.com/coins/images/5164/thumb/EURS_300x300.png' },
	'CORE': { name: 'Core', image: 'https://assets.coingecko.com/coins/images/28938/thumb/coredao.png' },
	'SCRT': { name: 'Secret', image: 'https://assets.coingecko.com/coins/images/11871/thumb/secret_logo.png' },
	'CELR': { name: 'Celer Network', image: 'https://assets.coingecko.com/coins/images/4379/thumb/Celr.png' },
	'ALI': { name: 'Artificial Liquid Intelligence', image: 'https://assets.coingecko.com/coins/images/22062/thumb/alethea-logo-transparent-colored.png' },
	'SFM': { name: 'SafeMoon', image: 'https://assets.coingecko.com/coins/images/21863/thumb/photo_2021-12-22_14.43.36.jpeg' },
	'API3': { name: 'API3', image: 'https://assets.coingecko.com/coins/images/13256/thumb/api3.jpg' },
	'AXL': { name: 'Axelar', image: 'https://assets.coingecko.com/coins/images/27277/thumb/V-65_xQ1_400x400.jpeg' },
	'LYXE': { name: 'LUKSO', image: 'https://assets.coingecko.com/coins/images/11423/thumb/1_QAHTciwVhD7SqVmfRW70Pw.png' },
	'PUNDIX': { name: 'Pundi X', image: 'https://assets.coingecko.com/coins/images/14571/thumb/vDyefsXq_400x400.jpg' },
	'RLC': { name: 'iExec RLC', image: 'https://assets.coingecko.com/coins/images/646/thumb/pL1VuXm.png' },

	AED: { name: 'UAE Dirham', 'image': `https://img.icons8.com/external-android-line-2px-amoghdesign/${icon_size}/${icon_color}/external-aed-currency-minima-24px-android-line-2px-amoghdesign.png` },
	AFN: { name: 'Afghan Afghani' },
	ALL: { name: 'Albanian Lek', 'image': default_icon_url + 'albanian-lek.png' },
	AMD: { name: 'Armenian Dram' },
	ANG: { name: 'Netherlands Antillian Guilder' },
	AOA: { name: 'Angolan Kwanza' },
	ARS: { name: 'Argentine Peso', 'image': peso },
	AUD: { name: 'Australian Dollar', 'image': default_icon_url + 'aud.png' },
	AWG: { name: 'Aruban Florin' },
	AZN: { name: 'Azerbaijani Manat' },
	BAM: { name: 'Bosnia and Herzegovina Mark' },
	BBD: { name: 'Barbados Dollar', 'image': dollar },
	BDT: { name: 'Bangladeshi Taka' },
	BGN: { name: 'Bulgarian Lev' },
	BHD: { name: 'Bahraini Dinar', 'image': `https://img.icons8.com/external-android-line-2px-amoghdesign/${icon_size}/${icon_color}/external-dinar-currency-minima-24px-android-line-2px-amoghdesign.png` },
	BIF: { name: 'Burundian Franc', 'image': franc },
	BMD: { name: 'Bermudian Dollar', 'image': dollar },
	BND: { name: 'Brunei Dollar', 'image': dollar },
	BOB: { name: 'Bolivian Boliviano' },
	BRL: { name: 'Brazilian Real', 'image': default_icon_url + 'real.png' },
	BSD: { name: 'Bahamian Dollar', 'image': dollar },
	BTN: { name: 'Bhutanese Ngultrum' },
	BWP: { name: 'Botswana Pula' },
	BYN: { name: 'Belarusian Ruble' },
	BZD: { name: 'Belize Dollar', 'image': dollar },
	CAD: { name: 'Canadian Dollar', 'image': default_icon_url + 'canadian-dollar.png' },
	CDF: { name: 'Congolese Franc', 'image': franc },
	CHF: { name: 'Swiss Franc', 'image': franc },
	CLP: { name: 'Chilean Peso', 'image': peso },
	CNY: { name: 'Chinese Renminbi' },
	COP: { name: 'Colombian Peso', 'image': peso },
	CRC: { name: 'Costa Rican Colon' },
	CUC: { name: 'Cuban Convertible Peso', 'image': peso },
	CUP: { name: 'Cuban Peso', 'image': peso },
	CVE: { name: 'Cape Verdean Escudo' },
	CZK: { name: 'Czech Koruna' },
	DJF: { name: 'Djiboutian Franc', 'image': franc },
	DKK: { name: 'Danish Krone' },
	DOP: { name: 'Dominican Peso', 'image': peso },
	DZD: { name: 'Algerian Dinar' },
	EGP: { name: 'Egyptian Pound', 'image': pound },
	ERN: { name: 'Eritrean Nakfa' },
	ETB: { name: 'Ethiopian Birr' },
	EUR: { name: 'Euro', 'image': default_icon_url + 'euro-pound-exchange.png' },
	FJD: { name: 'Fiji Dollar', 'image': dollar },
	FKP: { name: 'Falkland Islands Pound', 'image': pound },
	FOK: { name: 'Faroese Krona', 'image': krona },
	GBP: { name: 'Pound Sterling', 'image': pound },
	GEL: { name: 'Georgian Lari' },
	GGP: { name: 'Guernsey Pound', 'image': pound },
	GHS: { name: 'Ghanaian Cedi' },
	GIP: { name: 'Gibraltar Pound', 'image': pound },
	GMD: { name: 'Gambian Dalasi' },
	GNF: { name: 'Guinean Franc', 'image': franc },
	GTQ: { name: 'Guatemalan Quetzal' },
	GYD: { name: 'Guyanese Dollar', 'image': dollar },
	HKD: { name: 'Hong Kong Dollar', 'image': default_icon_url + 'hongkong-dollar.png' },
	HNL: { name: 'Honduran Lempira' },
	HRK: { name: 'Croatian Kuna' },
	HTG: { name: 'Haitian Gourde' },
	HUF: { name: 'Hungarian Forint' },
	IDR: { name: 'Indonesian Rupiah' },
	ILS: { name: 'Israeli New Shekel', 'image': default_icon_url + 'shekel.png' },
	IMP: { name: 'Manx Pound', 'image': pound },
	INR: { name: 'Indian Rupee', 'image': rupee },
	IQD: { name: 'Iraqi Dinar' },
	IRR: { name: 'Iranian Rial' },
	ISK: { name: 'Icelandic Krona', 'image': krona },
	JMD: { name: 'Jamaican Dollar', 'image': dollar },
	JOD: { name: 'Jordanian Dinar' },
	JPY: { name: 'Japanese Yen', 'image': default_icon_url + 'japanese-yen.png' },
	KES: { name: 'Kenyan Shilling' },
	KGS: { name: 'Kyrgyzstani Som', 'image': default_icon_url + 'kyrgyzstani-som.png' },
	KHR: { name: 'Cambodian Riel' },
	KID: { name: 'Kiribati Dollar', 'image': dollar },
	KMF: { name: 'Comorian Franc', 'image': franc },
	KRW: { name: 'South Korean Won', 'image': default_icon_url + 'won.png' },
	KWD: { name: 'Kuwaiti Dinar' },
	KYD: { name: 'Cayman Islands Dollar', 'image': dollar },
	KZT: { name: 'Kazakhstani Tenge' },
	LAK: { name: 'Lao Kip' },
	LBP: { name: 'Lebanese Pound', 'image': pound },
	LKR: { name: 'Sri Lanka Rupee', 'image': rupee },
	LRD: { name: 'Liberian Dollar', 'image': dollar },
	LSL: { name: 'Lesotho Loti' },
	LYD: { name: 'Libyan Dinar' },
	MAD: { name: 'Moroccan Dirham' },
	MDL: { name: 'Moldovan Leu' },
	MGA: { name: 'Malagasy Ariary' },
	MKD: { name: 'Macedonian Denar' },
	MMK: { name: 'Burmese Kyat' },
	MNT: { name: 'Mongolian Togrog' },
	MOP: { name: 'Macanese Pataca' },
	MRU: { name: 'Mauritanian Ouguiya' },
	MUR: { name: 'Mauritian Rupee', 'image': rupee },
	MVR: { name: 'Maldivian Rufiyaa' },
	MWK: { name: 'Malawian Kwacha' },
	MXN: { name: 'Mexican Peso', 'image': peso },
	MYR: { name: 'Malaysian Ringgit' },
	MZN: { name: 'Mozambican Metical' },
	NAD: { name: 'Namibian Dollar', 'image': dollar },
	NGN: { name: 'Nigerian Naira', 'image': default_icon_url + 'naira.png' },
	NIO: { name: 'Nicaraguan Cordoba' },
	NOK: { name: 'Norwegian Krone' },
	NPR: { name: 'Nepalese Rupee', 'image': rupee },
	NZD: { name: 'New Zealand Dollar', 'image': dollar },
	OMR: { name: 'Omani Rial' },
	PAB: { name: 'Panamanian Balboa' },
	PEN: { name: 'Peruvian Sol' },
	PGK: { name: 'Papua New Guinean Kina' },
	PHP: { name: 'Philippine Peso', 'image': peso },
	PKR: { name: 'Pakistani Rupee', 'image': rupee },
	PLN: { name: 'Polish Zloty', 'image': default_icon_url + 'zloty.png' },
	PYG: { name: 'Paraguayan Guarani' },
	QAR: { name: 'Qatari Riyal' },
	RON: { name: 'Romanian Leu', 'image': `https://img.icons8.com/external-android-line-2px-amoghdesign/${icon_size}/${icon_color}/external-leu-currency-minima-24px-android-line-2px-amoghdesign.png` },
	RSD: { name: 'Serbian Dinar' },
	RUB: { name: 'Russian Ruble', 'image': default_icon_url + 'ruble.png' },
	RWF: { name: 'Rwandan Franc', 'image': franc },
	SAR: { name: 'Saudi Riyal' },
	SBD: { name: 'Solomon Islands Dollar', 'image': dollar },
	SCR: { name: 'Seychellois Rupee', 'image': rupee },
	SDG: { name: 'Sudanese Pound', 'image': pound },
	SEK: { name: 'Swedish Krona', 'image': krona },
	SGD: { name: 'Singapore Dollar', 'image': dollar },
	SHP: { name: 'Saint Helena Pound', 'image': pound },
	SLL: { name: 'Sierra Leonean Leone' },
	SOS: { name: 'Somali Shilling' },
	SRD: { name: 'Surinamese Dollar', 'image': dollar },
	SSP: { name: 'South Sudanese Pound', 'image': pound },
	STN: { name: 'Sao Tome and Principe Dobra' },
	SYP: { name: 'Syrian Pound', 'image': pound },
	SZL: { name: 'Eswatini Lilangeni' },
	THB: { name: 'Thai Baht', 'image': default_icon_url + 'thai-baht.png' },
	TJS: { name: 'Tajikistani Somoni' },
	TMT: { name: 'Turkmenistan Manat' },
	TND: { name: 'Tunisian Dinar' },
	TOP: { name: 'Tongan Pa\'anga' },
	TRY: { name: 'Turkish Lira', 'image': default_icon_url + 'turkish-lira.png' },
	TTD: { name: 'Trinidad and Tobago Dollar', 'image': dollar },
	TVD: { name: 'Tuvaluan Dollar', 'image': dollar },
	TWD: { name: 'New Taiwan Dollar', 'image': dollar },
	TZS: { name: 'Tanzanian Shilling' },
	UAH: { name: 'Ukrainian Hryvnia', 'image': default_icon_url + 'ukrainian-hryvnia.png' },
	UGX: { name: 'Ugandan Shilling' },
	USD: { name: 'United States Dollar', 'image': dollar },
	UYU: { name: 'Uruguayan Peso', 'image': peso },
	UZS: { name: 'Uzbekistani So\'m' },
	VES: { name: 'Venezuelan Bolivar Soberano' },
	VND: { name: 'Vietnamese Dong' },
	VUV: { name: 'Vanuatu Vatu' },
	WST: { name: 'Samoan Tala' },
	XAF: { name: 'Central African CFA Franc', 'image': franc },
	XCD: { name: 'East Caribbean Dollar', 'image': dollar },
	XDR: { name: 'Special Drawing Rights' },
	XOF: { name: 'West African CFA franc', 'image': franc },
	XPF: { name: 'CFP Franc', 'image': franc },
	YER: { name: 'Yemeni Rial' },
	ZAR: { name: 'South African Rand' },
	ZMW: { name: 'Zambian Kwacha' }
}
